## Settings
title: "兄弟会天下第一"
owner: "Zero"
url: "https://akiritsu.github.io"
baseurl: "/pRoJEct-NeGYa"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "wjh199993@icloud.com"
github: "akiritsu/pRoJEct-NeGYa"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Designed By UbChina_Zero, All Rights Resereved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
